services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #   container_name: fapi
  #   environment:
  #     PORT: 8000
  #   ports:
  #     - '8000:8000'
  #   restart: "no"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fapi
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432
volumes:
  db_data: